[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200

[profile.sepolia]
rpc_url = "https://sepolia.infura.io/v3/1a34a37dbf4e44409187911e6573a844"
# Other specific configurations for the sepolia profile
